### ISSUE TITLE
SyntaxError : print(f"ROC-AUC{indexRun} = {auc:.4f}") 

### ISSUE THREAD

**Issue by rohitnitk** [Stream-AD/MIDAS#15]
When I run the Demo.py, I got the following error which I coulnt resolve after trying much. Why is that so? (  I dont think it is a syntax error also I dont find such syntax as well ) :-
`Seed = 1606470101	// In case of reproduction
#Records = 4554344	// Dataset is loaded
Time = 826ms	// Algorithm is finished
// Raw anomaly scores are exported to
// /home/rohit/MIDAS/MIDAS/temp/Score.txt
  File "/home/rohit/MIDAS/MIDAS/util/EvaluateScore.py", line 33
    print(f"ROC-AUC{indexRun} = {auc:.4f}")
                                         ^
SyntaxError: invalid syntax`
although output result is there in Score.txt

**Comment by liurui39660** [comment]
Hi, which version of python did you use? You can use `python -V` to find out its version. IIRC, this syntax is supported from python 3.6.

**Comment by rohitnitk** [comment]
@liurui39660  Thanks, my default python was 2.7. Issue is resolved by setting default python to python 3.8
