### ISSUE TITLE
How to decide whther edge is anomalous ?

### ISSUE THREAD

**Issue by rohitnitk** [Stream-AD/MIDAS#16]
In the Algorithm, how (on what basis ) you are deciding whether an edge is anomalous or not, given the anomaly score?  
(I've read the paper but couldn't find it )

**Comment by bhatiasiddharth** [comment]
The algorithm currently only outputs anomaly scores and not a binary value whether an edge is anomalous. You can either consider edges with high scores as anomalous or have a threshold based on domain expertise and consider edges having scores higher than that threshold as anomalous.

In the paper, we calculate the ROC-AUC using the anomaly scores generated by the algorithm and the ground truth available.
