### ISSUE TITLE
Any recommendation to normalize score?

### ISSUE THREAD

**Issue by munhouiani** [Stream-AD/MIDAS#19]
Hi,

Thank you for implementing this wonderful AD method!

I've read through your paper and the score is calculated as 
![image](https://user-images.githubusercontent.com/2124989/109770278-5751f800-7c36-11eb-86d5-f333aa84ab9b.png)

We usually use Unix timestamp to represent time, therefore the score we get is usually very large. Do you have any recommendations to narrow the value range?

Thank you!

**Comment by liurui39660** [comment]
For the timestamps, it's suggested to start from 1. You can divide timestamps by the desired time resolution, then subtract the smallest one and +1. This is how we did in experiments.
